### ISSUE TITLE
Determine if other GraphQL databases exist for other blockchains (apart from ETH and SOL)

### ISSUE THREAD

**Issue by IanMacDougall** [VizerISD/oceanmarketprotocol#6]
If you find any databases or GraphQL tools for other blockchains (e.g., bitcoin, cardano, etc.), drop links here!

**Comment by dhuang0212** [comment]
https://medium.com/coinmonks/best-crypto-apis-for-developers-5efe3a597a9f

Good link that has several ofthe current largest, successful Crypto and Blockchain APIs
